[versions]
conventionPlugin = "0.1.3"
androidx-benchmark = "1.3.3"
haze = "1.1.1"

[plugins]
conventionPlugin = { id = "com.mikepenz.convention.root", version.ref = "conventionPlugin" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-benchmark" }
cacheFixPlugin = { id = "org.gradle.android.cache-fix", version = "3.0.1" }

[libraries]
androidx-core = "androidx.core:core-ktx:1.15.0"
androidx-collection = "androidx.collection:collection:1.4.5"
androidx-activity-compose = "androidx.activity:activity-compose:1.9.3"

haze-core = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }

[bundles]
haze = ["haze-core", "haze-materials"]
