[versions]
haze = "2.0.0"

[libraries]
androidx-activity-compose = "androidx.activity:activity-compose:1.10.1"
haze-core = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-blur = { module = "dev.chrisbanes.haze:haze-blur", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-blur-materials", version.ref = "haze" }

[bundles]
haze = [
    "haze-core",
    "haze-blur",
    "haze-materials",
]
