[versions]
androidx-benchmark = "1.3.4"
haze = "1.6.0-beta01"

[plugins]
baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-benchmark" }
cacheFixPlugin = "org.gradle.android.cache-fix:3.0.1"

[libraries]
androidx-core = "androidx.core:core-ktx:1.16.0"
androidx-collection = "androidx.collection:collection:1.5.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.10.1"
haze-core = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }

[bundles]
haze = [
    "haze-core",
    "haze-materials",
]
